### PR TITLE
Count the command message for clearing messages.

### PR DESCRIPTION
**Pull request by shivaco**

### CODE REVIEW

**Comment by Kyousei** [comment]
Have you tested this works? I don't want to merge something that'll give me problems in future. :KappaPride:

**Comment by shivaco** [comment]
It does work. :Think:
image

**Comment by Kyousei** [comment]
Alright then.

**Comment by Deivedux** [comment]
I'm just saying, you can still change this to make it easier to read, and don't flood the code too much: `limit = number + 1`

**Comment by Kyousei** [comment]
Yeah sobaco, you are overcomplicating it sometimes. :Think:

**Comment by Deivedux** [comment]
Btw, that's how I ended up doing in my own bot, I tested how it would work with your code and just added that `+ 1` to "fix" it. So it's still kinda your fault @Kyousei that you STILL did not see that coming, and didn't even test how it would act in action.

**Comment by Kyousei** [comment]
I'm just here playing a game, dafuq you blaming me for. :LUL:

**Comment by Deivedux** [comment]
Just shut up and merge this shit already xD

**Comment by Kyousei** [comment]
:HYPERLUL:

**Pull request merged**
